### PR TITLE
Compatibility with 0.9.0-dev changes

### PR DESCRIPTION
**Pull request by mbcrocci**
This pull request makes a number of necessary changes to bring the library
up to zig 0.9.0-dev.400+6c11e9bb0

Namely:
- Removes unused parameters in functions and loops
- Removes `extern` enums
- Change of `opaque` syntax

It also fixes all the examples.

NOTE: one of the commits comments out the call to `fetchSubmodules` because I couldn't find the fix. Feel free to leave that commit out :^)

### CODE REVIEW

**Comment by Not-Nik** [comment]
Can't test this right now because of https://github.com/ziglang/zig/issues/5188 so I'll try to set up CI with gh actions, to at least build it on a linux system.

**Comment by Not-Nik** [comment]
Apparently CI doesn't work, likely because it doesn't have an X Window Server, so I'll merge this without further testing as it looks good to me. Before I do that though, can you further explain the `fetchSubmodules` change?

**Comment by mbcrocci** [comment]
Sorry for the late reply.

The call to `fetchSubmodules` failed to compile for me on the first line of the multi-line string with: `error: expected ',', found invalid bytes`

I finally found the reason and it seems it was because the file was saved with CRLF End of Line Sequence (I'm on Windows) which leaves a CR that is [no longer allowed in multi-line strings](https://github.com/ziglang/zig-spec/issues/38).

I reverted that change as a simple change of End of Line Sequence suffices to correct the issue.

**Comment by Not-Nik** [comment]
Alright, good to go :)

**Pull request merged**
